import AutoGenerateDaoPo.GeneratePo;
import com.sun.tools.javac.jvm.Gen;

/**
 * Created by SCY on 16/10/16.
 */
public class MainClass {

    public static void main(String[] args) throws Exception {
        GeneratePo generatePo = new GeneratePo();




        System.out.println("hello world");
    }


}
